[package]
name = "streaming-stats"
version = "0.2.2"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Experimental crate for computing basic statistics on streams."
documentation = "http://burntsushi.net/rustdoc/stats/"
homepage = "https://github.com/BurntSushi/rust-stats"
repository = "https://github.com/BurntSushi/rust-stats"
readme = "README.md"
keywords = ["statistics", "stats", "median", "mean", "stddev"]
license = "Unlicense/MIT"

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "std"]
std = []

[lib]
name = "stats"

[dependencies]
num-traits   = { git = "https://github.com/mesalock-linux/num-traits-sgx" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.2", optional = true }